INSERT INTO Categories (CategoryName, Description) VALUES 
('Electronics', 'Smartphones, Laptops, and Gadgets'),
('Furniture', 'Home and Office Furniture'),
('Clothing', 'Men, Women, and Kids Apparel'),
('Kitchenware', 'Cooking Tools and Appliances'),
('Books', 'Fiction, Science, and History'),
('Sports', 'Gym and Outdoor Equipment'),
('Beauty', 'Skincare and Cosmetics'),
('Toys', 'Educational and Fun Toys'),
('Automotive', 'Car Accessories and Tools'),
('Groceries', 'Daily Food and Drinks'),
('Pet Supplies', 'Pet Food and Accessories'),
('Garden', 'Plants and Gardening Tools'),
('Office Supplies', 'Stationery and Office Gear'),
('Jewelry', 'Watches and Fine Jewelry'),
('Music', 'Musical Instruments'),
('Health', 'Medical and Health Products'),
('Software', 'Digital Keys and Subscriptions'),
('Art', 'Painting and Craft Supplies'),
('Video Games', 'Consoles and Game Titles'),
('Industrial', 'Heavy Tools and Machinery');